// Tag pairs - opposing concepts on a spectrum
window.TAG_PAIRS = [
  ["Cold", "Hot"],
  ["Soft", "Hard"],
  ["Cheap", "Expensive"],
  ["Underrated", "Overrated"],
  ["Boring", "Exciting"],
  ["Common", "Rare"],
  ["Round", "Pointy"],
  ["Useless", "Useful"],
  ["Quiet", "Loud"],
  ["Small", "Big"],
  ["Safe", "Dangerous"],
  ["Sweet", "Salty"],
  ["Modern", "Ancient"],
  ["Realistic", "Fantastical"],
  ["Dumb move", "Smart move"],
  ["Bad gift", "Good gift"],
  ["Slow", "Fast"],
  ["Easy", "Hard"],
  ["Private", "Public"],
  ["Casual", "Formal"],
  ["Familiar", "Foreign"],
  ["Liquid", "Solid"],
  ["Natural", "Artificial"],
  ["Cute", "Creepy"],
  ["Simple", "Complex"],
  ["Forgettable", "Memorable"],
  ["Mild", "Spicy"],
  ["Smooth", "Rough"],
  ["Cheesy", "Classy"],
  ["Calm", "Chaotic"],
  ["Indoor", "Outdoor"],
  ["Optional", "Essential"],
  ["Quick read", "Long read"],
  ["Bad first date", "Good first date"],
  ["Weak superpower", "Strong superpower"],
  ["Bad smell", "Good smell"],
  ["Tastes bad", "Tastes good"],
  ["Bad name", "Cool name"],
  ["Hard to draw", "Easy to draw"],
  ["Bad pet", "Good pet"],
  ["Overrated movie", "Underrated movie"],
  ["Niche", "Mainstream"],
  ["Childish", "Mature"],
  ["Cold blooded", "Warm blooded"],
  ["Embarrassing", "Cool"],
  ["Hard to spell", "Easy to spell"],
  ["Worth the hype", "Not worth the hype"],
  ["Useless skill", "Useful skill"],
  ["Bad investment", "Good investment"],
  ["Indoor activity", "Outdoor activity"],
];
